version: "3"
services:
  web:
    build: .
    command: rake server
    ports:
      - "4567:4567"
    depends_on:
      - postgres
    environment:
      - CLIENT_ID="${CLIENT_ID}"
      - CLIENT_SECRET="${CLIENT_SECRET}"
      - REDIRECT_URI="${REDIRECT_URI}"
      - ERROR_URL="${ERROR_URL}"
      - SUCCESS_URL="${SUCCESS_URL}"
      - DATABASE_URL=postgres://postgres:postgres@postgres
  postgres:
    image: "postgres:11"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
volumes:
  postgres-data: