development:
  adapter: sqlite3
  encoding: utf8
  database: dog-api_development.db
  pool: 5
  username:
  password:

test:
  adapter: sqlite3
  encoding: utf8
  database: dog-api_test.db
  pool: 5
  username:
  password:

production:
  adapter: sqlite3
  encoding: utf8
  database: dog-api_production.db
  pool: 5
  username:
  password:

