development:
  adapter: sqlite3
  encoding: utf8
  database: dog-api_development.db
  pool: 5
  username:
  password:

test:
  adapter: sqlite3
  encoding: utf8
  database: dog-api_test.db
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['DB_NAME'] %>
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
