facts = [
  %(All dogs can be traced back 40 million years ago to a weasel-like animal called the Miacis which dwelled in trees and dens. The Miacis later evolved into the Tomarctus, a direct forbear of the genus Canis, which includes the wolf and jackal as well as the dog.),
  %(Ancient Egyptians revered their dogs. When a pet dog would die, the owners shaved off their eyebrows, smeared mud in their hair, and mourned aloud for days.),
  %(Small quantities of grapes and raisins can cause renal failure in dogs. Chocolate, macadamia nuts, cooked onions, or anything with caffeine can also be harmful.),
  %(Apple and pear seeds contain arsenic, which may be deadly to dogs.),
  %(Rock star Ozzy Osborne saved his wife Sharon’s Pomeranian from a coyote by tackling and wresting the coyote until it released the dog.),
  %(Dogs have sweat glands in between their paws.),
  %(In 2003, Dr. Roger Mugford invented the "wagometer," a device that claims to interpret a dog’s exact mood by measuring the wag of its tail.),
  %(Dogs have three eyelids. The third lid, called a nictitating membrane or "haw," keeps the eye lubricated and protected.),
  %(A dog’s shoulder blades are unattached to the rest of the skeleton to allow greater flexibility for running.),
  %(Puppies are sometimes rejected by their mother if they are born by cesarean and cleaned up before being given back to her.),
  %(The phrase "raining cats and dogs" originated in seventeenth-century England. During heavy rainstorms, many homeless animals would drown and float down the streets, giving the appearance that it had actually rained cats and dogs.),
  %(During the Middle Ages, Great Danes and Mastiffs were sometimes suited with armor and spiked collars to enter a battle or to defend supply caravans.),
  %(Pekingese and Japanese Chins were so important in the ancient Far East that they had their own servants and were carried around trade routes as gifts for kings and emperors. Pekingese were even worshipped in the temples of China for centuries.),
  %(The shape of a dog’s face suggests how long it will live. Dogs with sharp, pointed faces that look more like wolves typically live longer. Dogs with very flat faces, such as bulldogs, often have shorter lives.),
  %(After the fall of Rome, human survival often became more important than breeding and training dogs. Legends of werewolves emerged during this time as abandoned dogs traveling in packs commonly roamed streets and terrified villagers.),
  %(During the Middle Ages, mixed breeds of peasants’ dogs were required to wear blocks around their necks to keep them from breeding with noble hunting dogs. Purebred dogs were very expensive and hunting became the province of the rich.),
  %(The most dogs ever owned by one person were 5,000 Mastiffs owned by Kublai Khan.),
  %(The American Kennel Club, the most influential dog club in the United States, was founded in 1884.),
  %(The most popular male dog names are Max and Jake. The most popular female dog names are Maggie and Molly.),
  %(Scholars have argued over the metaphysical interpretation of Dorothy’s pooch, Toto, in the Wizard of Oz. One theory postulates that Toto represents Anubis, the dog-headed Egyptian god of death, because Toto consistently keeps Dorothy from safely returning home.),
  %(Weird dog laws include allowing police offers in Palding, Ohio, to bite a dog to quiet it. In Ventura County, California, cats and dogs are not allowed to have sex without a permit.),
  %(The first dog chapel was established in 2001. It was built in St. Johnsbury, Vermont, by Stephan Huneck, a children’s book author whose five dogs helped him recuperate from a serious illness.),
  %(Those born under the sign of the dog in Chinese astrology are considered to be loyal and discreet, though slightly temperamental.),
  %(In Iran, it is against the law to own a dog as a pet. However, if an owner can prove the dog is a guard or hunting dog, this restriction doesn’t apply. Muslim reticence concerning dogs is perhaps due to the fact that rabies has always been endemic in the Middle East.),
  %(The Mayans and Aztecs symbolized every tenth day with the dog, and those born under this sign were believed to have outstanding leadership skills.),
  %(The ancient Mbaya Indians of the Gran Chaco in South America believed that humans originally lived underground until dogs dug them up.),
  %(Plato once said that "a dog has the soul of a philosopher."),
  %(French poodles did not originate in France but in Germany ("poodle" comes from the German pudel or pudelhund, meaning "splashing dog"). Some scholars speculate the poodle’s puffs of hair evolved when hunters shaved the poodle for more efficient swimming, while leaving the pom-poms around the major joints to keep them warm.),
  %(The name of the dog on the Cracker Jacks box is Bingo. The Taco Bell Chihuahua is a rescued dog named Gidget.),
  %(The first dogs were self-domesticated wolves which, at least 12,000 years ago, became attracted to the first sites of permanent human habitation.),
  %(Dachshunds were bred to fight badgers in their dens.),
  %(Laika, a Russian stray, was the first living mammal to orbit the Earth, in the Soviet Sputnik spacecraft in 1957. Though she died in space, her daughter Pushnika had four puppies with President John F. Kennedy’s terrier, Charlie.),
  %(Dalmatians are completely white at birth.),
  %(The term "dog days of summer" was coined by the ancient Greeks and Romans to describe the hottest days of summer that coincided with the rising of the Dog Star, Sirius.),
  %(Alexander the Great is said to have founded and named a city Peritas, in memory of his dog.),
  %(In ancient Greece, kennels of dogs were kept at the sanctuary of Asclepius at Epidaurus. Dogs were frequently sacrificed there because they were plentiful, inexpensive, and easy to control. During the July 25 celebration of the kunophontis ("the massacre of dogs"), dog sacrifices were performed to appease the ancestors of Apollo’s son, Linos, who was devoured by dogs..),
  %(Dog trainers in ancient China were held in high esteem. A great deal of dog domestication also took place in China, especially dwarfing and miniaturization.),
  %(The ancient religion Zoroastrianism includes in its religious text titled the Zend Avesta a section devoted to the care and breeding of dogs.),
  %(The earliest European images of dogs are found in cave paintings dating back 12,000 years ago in Spain.),
  %(The dog was frequently depicted in Greek art, including Cerberus, the three-headed hound guarding the entrance to the underworld, and the hunting dogs which accompanied the virgin goddess of the chase, Diana.),
  %(During the Renaissance, detailed portraits of the dog as a symbol of fidelity and loyalty appeared in mythological, allegorical, and religious art throughout Europe, including works by Leonardo da Vinci, Diego Velázquez, Jan van Eyck, and Albrecht Durer.),
  %(A puppy is born blind, deaf, and toothless.),
  %(The Basenji is the world’s only barkless dog.),
  %(A dog most likely interprets a smiling person as baring their teeth, which is an act of aggression.),
  %(The origin of amputating a dog’s tail may go back to the Roman writer Lucius Columella’s (A.D. 4-70) assertion that tail docking prevented rabies.),
  %(One of Shakespeare’s most mischievous characters is Crab, the dog belonging to Launce in the Two Gentlemen of Verona. The word "watchdog" is first found in The Tempest.),
  %(President Franklin Roosevelt created a minor international incident when he claimed he sent a destroyer to the Aleutian Islands just to pick up his Scottish Terrier, Fala, who had been left behind.),
  %(Within hours of the September 11, 2001, attack on the World Trade Center, specially trained dogs were on the scene, including German Shepherds, Labs, and even a few little Dachshunds.),
  %(It costs approximately $10,000 to train a federally certified search and rescue dog.),
  %(The smallest dog on record was a matchbox-size Yorkshire Terrier. It was 2.5" tall at the shoulder, 3.5" from nose tip to tail, and weighed only 4 ounces.),
  %(Hollywood’s first and arguably best canine superstar was Rin Tin Tin, a five-day-old German Shepherd found wounded in battle in WWI France and adopted by an American soldier, Lee Duncan. He would sign his own contracts with his paw print.),
  %(At the end of WWI, the German government trained the first guide dogs for war-blinded soldiers.),
  %(A dog can locate the source of a sound in 1/600 of a second and can hear sounds four times farther away than a human can.),
  %(Touch is the first sense the dog develops. The entire body, including the paws, is covered with touch-sensitive nerve endings.),
  %(Eighteen muscles or more can move a dog’s ear.),
  %(The names of 77 ancient Egyptian dogs have been recorded. The names refer to color and character, such as Blackie, Ebony, Good Herdsman, Reliable, and Brave One.),
  %(In Egypt, a person bitten by a rabid dog was encouraged to eat the roasted liver of a dog infected with rabies to avoid contracting the disease. The tooth of a dog infected with rabies would also be put in a band tied to the arm of the person bitten. The menstrual blood of a female dog was used for hair removal, while dog genitals were used for preventing the whitening of hair.),
  %(In early Christian tradition, Saint Christopher, the patron saint of travelers, is sometimes depicted with a dog’s head.),
  %(The oldest known dog bones were found in Asia and date as far back as 10,000 B.C. The first identifiable dog breed appeared about 9000 B.C. and was probably a type of Greyhound dog used for hunting.),
  %(There are an estimated 400 million dogs in the world.),
  %(The U.S. has the highest dog population in the world. France has the second highest.),
  %(Dog nose prints are as unique as human finger prints and can be used to identify them.),
  %(Bloodhound dogs have a keen sense of smell and have been used since the Middle Ages to track criminals.),
  %(It is much easier for dogs to learn spoken commands if they are given in conjunction with hand signals or gestures.),
  %(Dogs in a pack are more likely to chase and hunt than a single dog on its own. Two dogs are enough to form a pack.),
  %(Dogs can see in color, though they most likely see colors similar to a color-blind human. They can see better when the light is low.),
  %(Petting dogs is proven to lower blood pressure of dog owners.),
  %(Dogs have lived with humans for over 14,000 years. Cats have lived with people for only 7,000 years.),
  %(Zorba, an English mastiff, is the biggest dog ever recorded. He weighed 343 pounds and measured 8’ 3" from his nose to his tail.),
  %(The average dog can run about 19 mph. Greyhounds are the fastest dogs on Earth and can run at speeds of 45 mph.),
  %(One female dog and her female children could produce 4,372 puppies in seven years.),
  %(The most popular dog breed in Canada, U.S., and Great Britain is the Labrador retriever.),
  %(Greyhounds appear to be the most ancient dog breed. "Greyhound" comes from a mistake in translating the early German name Greishund, which means "old (or ancient) dog," not from the color gray.),
  %(The oldest dog on record was an Australian cattle dog named Bluey who lived 29 years and 5 months. In human years, that is more than 160 years old.),
  %(Most experts believe humans domesticated dogs before donkeys, horses, sheep, goats, cattle, cats, or chickens.),
  %(A person standing still 300 yards away is almost invisible to a dog. But a dog can easily identify its owner standing a mile away if the owner is waving his arms.),
  %(Dogs with big, square heads and large ears (like the Saint Bernard) are the best at hearing subsonic sounds.),
  %(Dogs can smell about 1,000 times better than humans. While humans have 5 million smell-detecting cells, dogs have more than 220 million. The part of the brain that interprets smell is also four times larger in dogs than in humans.),
  %(Some dogs can smell dead bodies under water, where termites are hiding, and natural gas buried under 40 feet of dirt. They can even detect cancer that is too small to be detected by a doctor and can find lung cancer by sniffing a person’s breath.),
  %(Dogs have a wet nose to collect more of the tiny droplets of smelling chemicals in the air.),
  %(Dogs like sweets a lot more than cats do. While cats have around only 473 taste buds, dogs have about 1,700 taste buds. Humans have approximately 9,000.),
  %(Different smells in the a dog’s urine can tell other dogs whether the dog leaving the message is female or male, old or young, sick or healthy, happy or angry.),
  %(Male dogs will raise their legs while urinating to aim higher on a tree or lamppost because they want to leave a message that they are tall and intimidating. Some wild dogs in Africa try to run up tree trunks while they are urinating to appear to be very large.),
  %(In Croatia, scientists discovered that lampposts were falling down because a chemical in the urine of male dogs was rotting the metal.),
  %(Dogs are about as smart as a two- or three-year-old child. This means they can understand about 150-200 words, including signals and hand movements with the same meaning as words.),
  %(Countess Karlotta Libenstein of Germany left approximately $106 million to her Alsatin, Gunther III, when she died in 1992.),
  %(A lost Dachshund was found swallowed whole in the stomach of a giant catfish in Berlin on July 2003.),
  %(In Australia, a man who was arrested for drug possession argued his civil rights were violated when the drug-sniffing dog nuzzled his crotch. While the judge dismissed the charges, they were later reinstated when a prosecutor pointed out that in the animal kingdom, crotch nuzzling was a friendly gesture.),
  %(The Beagle came into prominence in the 1300s and 1400s during the days of King Henry VII of England. Elizabeth I was fond of Pocket Beagles, which were only 9" high.),
  %(The best dog to reportedly attract a date is the Golden Retriever. The worst is the Pit Bull.),
  %(The Akita is one of the most challenging dogs to own. Some insurance companies have even characterized it as the #1 "bad dog" and may even raise an Akita owner’s homeowner insurance costs.),
  %(The Beagle and Collie are the nosiest dogs, while the Akbash Dog and the Basenji are the quietest.),
  %(One survey reports that 33% of dog owners admit they talk to their dogs on the phone or leave messages on answering machines while they are away..),
  %(Thirty percent of all Dalmatians are deaf in one or both ears. Because bulldogs have extremely short muzzles, many spend their lives fighting suffocation. Because Chihuahuas have such small skulls, the flow of spinal fluid can be restricted, causing hydrocephalus, a swelling of the brain.),
  %(The grief suffered after a pet dog dies can be the same as that experienced after the death of a person.),
  %(There are almost 5 million dog bites per year; children are the main victims. Dog bites cause losses of over $1 billion a year.),
  %(A person should never kick a dog facing him or her. Some dogs can bite 10 times before a human can respond.),
  %(The most intelligent dogs are reportedly the Border Collie and the Poodle, while the least intelligent dogs are the Afghan Hound and the Basenji.),
  %(One kind of Pekingese is referred to as a "sleeve" because it was bred to fit into a Chinese empress’ sleeves, which was how it was often carried around.),
  %(Is it a duck... or a dog? The Newfoundland breed has a water resistant coat and webbed feet. This dog was originally bred to help haul nets for fishermen and rescuing people at risk of drowning.),
  %(It pays to be a lap dog. Three dogs (from First Class cabins!) survived the sinking of the Titanic – two Pomeranians and one Pekingese.),
  %(A Beatles hit. It’s rumored that, at the end of the Beatles song, "A Day in the Life," Paul McCartney recorded an ultrasonic whistle, audible only to dogs, just for his Shetland sheepdog.),
  %(Wow, check out those choppers! Puppies have 28 teeth and normal adult dogs have 42.),
  %(Chase that tail! Dogs chase their tails for a variety of reasons: curiosity, exercise, anxiety, predatory instinct or, they might have fleas! If your dog is chasing his tail excessively, talk with your vet.),
  %(Seeing spots? Or not...  Dalmatian puppies are pure white when they are born and develop their spots as they grow older.),
  %(Dogs do dream! Dogs and humans have the same type of slow wave sleep (SWS) and rapid eye movement (REM) and during this REM stage dogs can dream. The twitching and paw movements that occur during their sleep are signs that your pet is dreaming),
  %(No night vision goggles needed! Dogs’ eyes contain a special membrane, called the tapetum lucidum, which allows them to see in the dark.),
  %(Pitter patter. A large breed dog’s resting heart beats between 60 and 100 times per minute, and a small dog breed’s heart beats between 100-140. Comparatively, a resting human heart beats 60-100 times per minute.),
  %(If your dog’s acting funny, get out the umbrella! According to a Petside.com/Associated Press poll, 72% of dog owners believe their dog can detect when stormy weather is on the way.),
  %(It’s not a fever... A dog’s normal temperature is between 101 and 102.5 degrees Fahrenheit. How much do you know about dog health? Take our Doggy First Aid Quiz!),
  %(Is something wet? Unlike humans who sweat everywhere, dogs only sweat through the pads of their feet.),
  %(Here’s looking at you. Dogs have three eyelids, an upper lid, a lower lid and the third lid, called a nictitating membrane or "haw," which helps keep the eye moist and protected.),
  %(Americans love dogs! 62% of U.S. households own a pet, which equates to 72.9 million homes),
  %(Move over Rover! 45% of dogs sleep in their owner’s bed (we’re pretty sure a large percentage also hog the blankets!)),
  %(Why are dogs’ noses so wet? Dogs’ noses secrete a thin layer of mucous that helps them absorb scent. They then lick their noses to sample the scent through their mouth.),
  %(Yummy! Dogs have about 1,700 taste buds. Humans have approximately 9,000 and cats have around 473.),
  %(Watch that plate of cookies! A Dog’s sense of smell is 10,000 – 100,000 times more acute as that of humans.),
  %(It’s not so black and white. It’s a myth that dogs only see in black and white. In fact, it’s believed that dogs see primarily in blue, greenish-yellow, yellow and various shades of gray.),
  %(Did you hear that? Sound frequency is measured in Hertz (Hz). The higher the Hertz, the higher-pitched the sound. Dogs hear best at 8,000 Hz, while humans hear best at around 2,000 Hz.),
  %(Express yourself. Dogs’ ears are extremely expressive. It’s no wonder! There are more than a dozen separate muscles that control a dog’s ear movements.),
  %(Growing up. While the Chow Chow dogs are well known for their distinctive blue-black tongues, they’re actually born with pink tongues. They turn blue-black at 8-10 weeks of age.),
  %(Why do they do that? When dogs kick after going to the bathroom, they are using the scent glands on their paws to further mark their territory.),
  %(No, it’s not just to make themselves look adorable. Dogs curl up in a ball when they sleep due to an age-old instinct to keep themselves warm and protect their abdomen and vital organs from predators.),
  %(Dogs are capable of understanding up to 250 words and gestures, can count up to five and can perform simple mathematical calculations. The average dog is as intelligent as a two-year-old child.),
  %(Some stray Russian dogs have figured out how to use the subway system in order to travel to more populated areas in search of food.),
  %(Dogs don't enjoy being hugged as much as humans and other primates. Canines interpret putting a limb over another animal as a sign of dominance.),
  %(Two stray dogs in Afghanistan saved 50 American soliders. A Facebook group raised $21,000 to bring the dogs back to the US and reunite them with the soldiers.),
  %(The Beatles song "A day in the Life" has an extra high-pitched whistle, audible only to dogs. It was recorded by Paul McCartney for the enjoyment of his Shetland sheepdog.),
  %(This pup, Nesbit, earned over one million Delta airline miles in his life and had his own frequent flier card.),
  %(One of Michael Vick's former fighting dogs, Leo, went on to be a therapy dog who comforted dying children.),
  %(Service dogs are trained to know when they are on duty. When their harness is on, they know it's business time. When you take it off, the pups immediately become playful and energetic.),
  %(Tiger Woods stuttered as a child and used to talk to his dog until he fell asleep in an effort to get rid of it.),
  %(Seeing eye dogs pee and poo on command so that their owners can clean up after them. (The command is usually "Get busy!" and pups will pace back and forth until they do their business.) Male dogs are also trained to do their business without lifting their leg.),
  %(n ancient China, an emperor's last line of defense was a small Pekingese dog literally hidden up his sleeve.),
  %(When Lord Byron was informed that his dog was not allowed to come with him to Cambridge Trinity College, he retaliated by bringing a bear instead.),
  %(In 1860's San Francisco, two stray dogs who were best friends became local celebrities. Their exploits were celebrated in local papers and they were granted immunity from the city's dog catchers.),
  %(There is a dog-shaped building in New Zealand.),
  %(This dog, Naki'o, lost all of his legs to frostbite in Colorado, but now has four prosthetic legs and can run around like normal.),
  %(The wetness of a dog's nose is essential for determining what direction a smell is coming from.),
  %(Hyenas aren't actually dogs. They are more closely related to cats.),
  %(Spiked dog collars were invented in ancient Greece and were originally designed to protect dogs throats from wolf attacks.),
  %(Baks the blind boxer has a seeing eye goose named Buttons. Buttons the four-year-old goose leads her pup around everywhere either by hanging onto him with her neck, or by honking to tell him which way to go.),
  %('Frito Feet' is the name of the phenomenon in which the bacteria on a dog's paws cause them to smell like corn chips. Because a pup's feet are in constant contact with the ground, they pick up tons of microorganisms in their paws. When dogs cool off by sweating through the pads of their feet, the combo of moisture and bacteria releaces a nutty, popcorn-like aroma. Basically it's dog B.O.),
  %(It is a myth that dogs are color blind. They can actually see in color, just not as vividly as humans. It is akin to our vision at dusk.),
  %(Dogs DO have better low-light vision than humans because of a special light-reflecting layer behind their retinas.),
  %(A German Shepherd guide dog led her blind companion the entire 2,100 mile Appalachian Trail.),
  %(If never spayed or neutered, a female dog, her mate, and their puppies could produce over 66,000 dogs in 6 years!),
  %(Dogs’ only sweat glands are between their paw pads.),
  %(Like human babies, Chihuahuas are born with a soft spot in their skull which closes with age.),
  %(The breed Lundehune has 6 toes and can close its ears.),
  %(Teddy Roosevelt’s dog, Pete, ripped a French ambassador’s pants off at the White House.),
  %(President Lyndon Johnson had two beagles named Him and Her.),
  %(Franklin Roosevelt spent $15,000 for a destroyer to pick up his Scottie in the Aleutian Islands.),
  %(In Roman times, mastiffs donned light armor and were sent after mounted knights.),
  %(The Russians trained dogs during WWII to run suicide missions with mines strapped to their backs.),
  %(A dog’s mouth exerts 150–200 pounds of pressure per square inch with some dogs exerting up to 450 pounds per square inch.),
  %(A one year old dog is as physically mature as a 15 year old human.),
  %(The U.S. has the highest dog population in the world.),
  %(France has the 2nd highest dog population.),
  %(The average city dog lives 3 years longer than a country dog.),
  %(Eighty-seven percent of dog owners say their dog curls up beside them or at their feet while they watch T.V.),
  %(Dogs can be trained to detect epileptic seizures in humans.),
  %(Fifteen people die in the U.S. every year from dog bites.),
  %(In 2002 alone, more people in the U.S. were killed by dogs than by sharks in the past 100 years.),
  %(Gidget is the name of the Taco Bell dog.),
  %(Newfoundlands are great swimmers because of their webbed feet.),
  %(Basset Hounds cannot swim.),
  %(Greyhounds are the fastest dogs on earth, with speeds of up to 45 miles per hour.),
  %(Bingo is the name of the dog on the side of the Cracker Jack box.),
  %(The bible mentions dogs 14 times.),
  %(Three dogs survived the sinking of the Titanic: a Newfoundland, a Pomeranian, and a Pekingese.),
  %(The Labrador Retriever is the #1 favorite breed in the U.S., Canada, and the U.K.),
  %(Obesity is the #1 health problem among dogs.),
  %(An estimated 1,000,000 dogs in the U.S. have been named as the primary beneficiaries in their owner’s will.),
  %(An American Animal Hospital Association poll found that 33% of dog owners admit to talking to their dogs on the phone and leaving answering machine messages for them while away.),
  %(Dogs’ nose prints are as unique as a human’s finger prints, and can be used to accurately identify them.),
  %(At the end of the Beatles’ song "A Day in the Life," a high-pitched dog whistle was recorded by Paul McCartney for his sheepdog.),
  %(Seventy percent of people sign their pet’s name on greeting and holiday cards.),
  %(Fifty-eight percent of people put pets in family and holiday portraits.),
  %(There are only 350 Cisky Terriers in the world, possibly making it the rarest breed.),
  %(The phrase "raining cats and dogs" originated in 17th century England when it is believed that many cats and dogs drowned during heavy periods of rain.),
  %(Dogs have no sense of time.),
  %(Humans have kept dogs as pets for over 12,000 years.),
  %(The largest breed of dog is the Irish Wolfhound.),
  %(The world’s smallest dog breed is the Chihuahua.),
  %(The St. Bernard is the heaviest dog breed.),
  %(Only dogs and humans have prostates.),
  %(Dogs do not have an appendix.),
  %(Every dog on earth likely descended from a species knows as the Tomarctus – a creature that roamed the earth over 15 million years ago.),
  %(The oldest known breed is likely the Saluki, originally trained by Egyptians to help them track game.),
  %(In 1957, Laika became the first living being in space via an earth satellite and JFK’s terrier, Charlie, fathered 4 puppies with Laika’s daughter.),
  %(An African wolf dog known as the Basenji is the only dog in the world that cannot bark.),
  %(There are 703 breeds of purebred dogs.),
  %(Dachshunds were originally bred for fighting badgers.),
  %(The world’s smartest dogs are thought to be (1) the Border Collie, (2) the Poodle, and (3) the Golden Retriever and the dumbest dog is believed to be the Afghan Hound.),
  %(A dog’s sense of smell is more than 100,000 times stronger than that of a human.),
  %(Dogs need a strong sense of smell because their eyesight is not as keen as a human’s.),
  %(Dogs judge objects first by their movement, then by their brightness, and lastly by their shape.),
  %(Chocolate contains a substance known as theobromine (similar to caffeine) which can kill dogs or, at the very least, make them violently ill.),
  %(George Washington had 36 dogs–all Foxhounds–with one named Sweetlips.),
  %(All dogs are identical in anatomy, with 321 bones and 42 permanent teeth.),
  %(Smaller breeds mature faster than larger breeds.),
  %(Female dogs are only ready to mate–"in heat"–twice a year for a total of roughly 20 days.),
  %(Puppies sleep 90% of the day for their first few weeks.),
  %(Rin Tin Tin was the first Hollywood dog star and he really signed his movie contracts – all 22 of them – with a paw-print.),
  %(Toto in The Wizard of Oz was played by a female Cairn Terrier named Terry.),
  %(A dog’s vision is not fully developed until after the first month.),
  %(Dogs have twice as many muscles to move their ears as people.),
  %(The longer a dog’s nose, the more effective it’s internal cooling system.),
  %(An elderly woman was saved by her 12-pound Yorkshire Terrier, who fought off an 80- pound Akita, and survived with only 9 stitches.),
  %(U.S. Customs dogs "Rocky" and "Barco" were so good at patrolling the border that Mexican drug lords put a $300,000 bounty on their heads.),
  %(Dogs are all direct descendants of wolves.),
  %(Wolves and dogs can mate to produce fertile offspring.),
  %(Female wolves have been known to travel great distances to regurgitate full meals for their hungry pups.),
  %(Cerberus was the tri-headed dog that guarded the underworld in Greek mythology,),
  %(A dog’s pregnancy lasts for approximately 60 days.),
  %(Dogs’ sense of hearing is more than ten times more acute than a human’s.),
  %(Humans can detect sounds at 20,000 times per second, while dogs can sense frequencies of 30,000 times per second.),
  %(The earliest dog fossil dates back to nearly 10,000 B.C.),
  %(Bloodhounds are prized for their ability to single out and identify a number of scents simultaneously.),
  %(Dalmatian puppies are born completely white.),
  %(The ancient Chinese carried Pekingese puppies in the sleeves of their robes.),
  %(Boxers are so named because of their manner of playing using their front paws.),
  %(All breeds of dog have been found to attack livestock, from 3-month-old puppies to 13-year-old poodles.),
  %(A dog’s heart beats up to 120 times per minute, or 50% faster than the average human heartbeat of 80 times per minute),
  %(The oldest dog on record – a Queensland Heeler named Bluey – was 29 years, 5 months old.),
  %(Davy Crockett had a dog named Sport.),
  %(Dogs were first domesticated by cavemen.),
  %(Dogs live an average of 15 years.),
  %(Many foot disorders in dogs are simply an issue of too-long toenails.),
  %(More than 5,000,000 puppies are born in the U.S. every year.),
  %(More than 1 in 3 American families own a dog.),
  %(Average body temperature for a dog is 101.2 degrees.),
  %(The Girl Scouts and Boy Scouts both offer merit badges in dog care.),
  %(Dogs are natural pack animals.),
  %(Dogs are naturally submissive to any creature with higher pack status, human or canine.),
  %(Puppies’ eyes do not fully open until they’re about 12 days old.),
  %(Dogs with little human contact in the first three months typically don’t make good pets.),
  %(The Chihuahua was named after the state in Mexico where they were discovered.)
]
facts.map!{|f| { body: f } }
Fact.create(facts)
